keepcalm:
  security:
    jwt:
      issuer: Keepcalm Auth
      audience: Keepcalm
      secret: thisIsAVerySecureAndLongJWTSecretThatCanBeUsedForTesting
    endpoints:
      admin:
        - "/api/salary/**"
      user:
        - "/api/document/**"
      unsecured:
        - "/unsecure"
